@startuml uml_agent_local_llm_custom
start

:질문;

if (도구 자동 선택인지?) then (Yes)
  #Yellow:액션 추출 (Qwen2);

  :액션에 맞는 도구 사용 (검색);
else (No)
  :도구 사용 (검색);
endif

if (검색된 문서가 있는지?) then (Yes)
  :검색된 문서 전처리
  (내용과 출처만 파싱);
  
  partition "**컨텍스트 포함 체인 사용**" {
      :컨텍스트 포함 프롬프트;
      #PaleGreen:답변 생성 (EEVE);
      :후처리
      (출처 명시);
  }
else (No)
  partition "**컨텍스트 미포함 체인 사용**" {
      :컨텍스트 미포함 프롬프트;
      #PaleGreen:답변 생성 (EEVE);
  }
endif

stop
@enduml